config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "employees#index"

  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true
    validates :role, presence: true
    validates :salary, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index 
        @employees = Employee.all
    end

    def show
        @employees = Employee.find(params[:id])
    end
    
    def new
        @employees = Employee.new
    end

    def create
        @employees = Employee.new(employee_params)
        if @employees.save
          flash[:success] = "Employee successfully added"
          redirect_to @employees
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end

    def edit
        @employees = Employee.find(params[:id])
    end

    def update
        @employees = Employee.find(params[:id])
        if @employees.update(employee_params)
            redirect_to @employees
        else
            render 'edit'
        end
    end

    def destroy
        @employees = Employee.find(params[:id])
        @employees.destroy

        redirect_to root_path
    end
    
    private

    def employee_params
        params.require(:employee).permit(:name, :age, :role, :salary)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <%= form_with model: @employees do |form| %>
        <div>
            <%= form.label :name %> 
            <%= form.text_field :name %><br><hr>
        </div>
        <div>
            <%= form.label :age %>
            <%= form.number_field :age %><br> <hr>
        </div>
        <div>
            <%= form.label :role %> 
            <%= form.text_field :role %><br><hr>
        </div>
        <div>
            <%= form.label :salary%> 
            <%= form.number_field :salary%><br><hr>
        </div>
        <div class="button">
            <%= form.submit %> <br><hr>
        </div>
    <% end %>
</body>
</html>

app/views/employees/edit.html.erb
<h1>Edit the information of the employee</h1>
 
<%= render 'form', employees: @employees %>

app/views/employees/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Employee List</title>
  </head>
  <body>
    <div class="container" style="background-color:yellow; max-width: max-content; flex-direction: column;">
        <!-- Content here -->
        <h1>These are the list of employees in this organization</h1>
    </div>
        <ol>
            
            <% @employees.each do |employee|%>
                <li>
                    <%= link_to employee.name, employee %>
                </li>
            <% end %>
            
        </ol>

        <%= link_to "Add a New Employee", new_employee_path %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/employees/new.html.erb
<h1> Add an new employee to the database </h1>
<h1 style="color: blue;"> Employee Registration Form </h1>
<%= render 'form', employees: @employees %>

app/views/employees/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= employees_path %></title>
</head>
<body>

    <h1 style="flex: auto;">Name:  <%= @employees.name %></h1>
    <h2>Age:  <%= @employees.age %></h2>
    <h3>Role:  <%= @employees.role %></h3>
    <h4>Salary:  <%= @employees.salary%></h4>
    <%= link_to "Edit", edit_employee_path(@employees) %>
    <%= link_to "Delete", employee_path(@employees), method: :delete, data: { confirm: "Are you sure?" }%>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>